name: SILPH_Q
description: Revolutionary Security

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_secure_storage: ^3.3.2
  flutter_signin_button: ^1.0.0
  custom_radio_button: ^0.0.3
  string_validator: ^0.1.4
  socket_io_client: ^0.9.9
  pull_to_refresh: ^1.5.7
  google_sign_in: ^4.0.4
  pretty_qr_code: ^1.0.1
  barcode_scan: ^3.0.0
  pointycastle: ^1.0.2
  bloc_pattern: ^2.5.1
  qr_flutter: ^3.2.0
  flushbar: ^1.10.0
  encrypt: ^4.0.0
  asn1lib: ^0.5.8
  rxdart: ^0.23.1
  zefyr: 0.10.0
  intl: ^0.16.1
  uuid: ^2.0.4
  dio: ^3.0.9

  flutter:
    sdk: flutter


dev_dependencies:
  flutter_launcher_icons: ^0.7.4
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/icon.jpg
    - assets/qr-overlap.png
    - assets/logo-emboss-ital.png
    - assets/logo-emboss-silph.png

  fonts:
    - family: SF-Pro-Text-Regular
      fonts:
        - asset: assets/SF-Pro-Text-Regular.otf

    - family: Orbitron-black
      fonts:
        - asset: assets/orbitron-black.ttf

    - family: Cedarville
      fonts:
        - asset: assets/Cedarville.ttf

    - family: Poppins-Reg
      fonts:
        - asset: assets/Poppins-Regular.ttf

    - family: Poppins
      fonts:
        - asset: assets/Poppins-Bold.ttf

    - family: Ducks
      fonts:
        - asset: assets/ducks.ttf

    - family: SF-Pro-Text-Bold
      fonts:
        - asset: assets/SF-Pro-Text-Bold.otf

    - family: Calibre-Semibold
      fonts:
        - asset: assets/Calibre-Semibold.otf

    - family: CustomIcons
      fonts:
        - asset: assets/custom_icons.ttf
